export enum Types {
  LOAD_USER_DETAILS_REQUEST = '@user-details/LOAD_USER_DETAILS_REQUEST',
  LOAD_USER_DETAILS_SUCCESS = '@user-details/LOAD_USER_DETAILS_SUCCESS',
  LOAD_USER_DETAILS_FAILURE = '@user-details/LOAD_USER_DETAILS_FAILURE',
}
